export const PLAYER_SETUP = [
  { id: 'human', name: 'You', color: '#60A5FA', isAI: false },
  { id: 'ai-1', name: 'AI 1', color: '#F87171', isAI: true },
  { id: 'ai-2', name: 'AI 2', color: '#4ADE80', isAI: true },
  { id: 'ai-3', name: 'AI 3', color: '#FBBF24', isAI: true },
];

export const STARTING_CASH = 300;
export const LOW_CASH_THRESHOLD = 120;

export const TILES = [
  { id: 0, name: 'GO', type: 'go' },
  { id: 1, name: 'Mediterranean Ave', type: 'property', price: 60, rent: 8, colorGroup: 'brown' },
  { id: 2, name: 'Community Chest', type: 'rest' },
  { id: 3, name: 'Baltic Ave', type: 'property', price: 60, rent: 10, colorGroup: 'brown' },
  { id: 4, name: 'Income Tax', type: 'rest' },
  { id: 5, name: 'Reading Railroad', type: 'property', price: 110, rent: 14 },
  { id: 6, name: 'Oriental Ave', type: 'property', price: 100, rent: 12, colorGroup: 'lightBlue' },
  { id: 7, name: 'Chance', type: 'rest' },
  { id: 8, name: 'Vermont Ave', type: 'property', price: 100, rent: 12, colorGroup: 'lightBlue' },
  { id: 9, name: 'Connecticut Ave', type: 'property', price: 120, rent: 14, colorGroup: 'lightBlue' },
  { id: 10, name: 'Jail / Visit', type: 'rest' },
  { id: 11, name: 'St. Charles Place', type: 'property', price: 140, rent: 16, colorGroup: 'pink' },
  { id: 12, name: 'Electric Company', type: 'property', price: 150, rent: 18 },
  { id: 13, name: 'States Ave', type: 'property', price: 140, rent: 16, colorGroup: 'pink' },
  { id: 14, name: 'Virginia Ave', type: 'property', price: 160, rent: 18, colorGroup: 'pink' },
  { id: 15, name: 'Pennsylvania RR', type: 'property', price: 170, rent: 20 },
  { id: 16, name: 'St. James Place', type: 'property', price: 180, rent: 20, colorGroup: 'orange' },
  { id: 17, name: 'Community Chest', type: 'rest' },
  { id: 18, name: 'Tennessee Ave', type: 'property', price: 180, rent: 22, colorGroup: 'orange' },
  { id: 19, name: 'New York Ave', type: 'property', price: 200, rent: 24, colorGroup: 'orange' },
  { id: 20, name: 'Free Parking', type: 'rest' },
  { id: 21, name: 'Kentucky Ave', type: 'property', price: 220, rent: 24, colorGroup: 'red' },
  { id: 22, name: 'Chance', type: 'rest' },
  { id: 23, name: 'Indiana Ave', type: 'property', price: 220, rent: 24, colorGroup: 'red' },
  { id: 24, name: 'Illinois Ave', type: 'property', price: 240, rent: 26, colorGroup: 'red' },
  { id: 25, name: 'B&O Railroad', type: 'property', price: 240, rent: 26 },
  { id: 26, name: 'Atlantic Ave', type: 'property', price: 260, rent: 28, colorGroup: 'yellow' },
  { id: 27, name: 'Ventnor Ave', type: 'property', price: 260, rent: 28, colorGroup: 'yellow' },
  { id: 28, name: 'Water Works', type: 'property', price: 260, rent: 30 },
  { id: 29, name: 'Marvin Gardens', type: 'property', price: 280, rent: 30, colorGroup: 'yellow' },
  { id: 30, name: 'Go To Jail', type: 'rest' },
  { id: 31, name: 'Pacific Ave', type: 'property', price: 300, rent: 32, colorGroup: 'green' },
  { id: 32, name: 'North Carolina Ave', type: 'property', price: 300, rent: 34, colorGroup: 'green' },
  { id: 33, name: 'Community Chest', type: 'rest' },
  { id: 34, name: 'Pennsylvania Ave', type: 'property', price: 320, rent: 36, colorGroup: 'green' },
  { id: 35, name: 'Short Line', type: 'property', price: 320, rent: 36 },
  { id: 36, name: 'Chance', type: 'rest' },
  { id: 37, name: 'Park Place', type: 'property', price: 350, rent: 40, colorGroup: 'darkBlue' },
  { id: 38, name: 'Luxury Tax', type: 'rest' },
  { id: 39, name: 'Boardwalk', type: 'property', price: 400, rent: 44, colorGroup: 'darkBlue' },
];

export const BOARD_POSITIONS = [
  // Top row: left -> right
  { row: 0, col: 0 },
  { row: 0, col: 1 },
  { row: 0, col: 2 },
  { row: 0, col: 3 },
  { row: 0, col: 4 },
  { row: 0, col: 5 },
  { row: 0, col: 6 },
  { row: 0, col: 7 },
  { row: 0, col: 8 },
  { row: 0, col: 9 },
  { row: 0, col: 10 },
  // Right column: top -> bottom (excluding top-right corner)
  { row: 1, col: 10 },
  { row: 2, col: 10 },
  { row: 3, col: 10 },
  { row: 4, col: 10 },
  { row: 5, col: 10 },
  { row: 6, col: 10 },
  { row: 7, col: 10 },
  { row: 8, col: 10 },
  { row: 9, col: 10 },
  { row: 10, col: 10 },
  // Bottom row: right -> left (excluding bottom-right corner)
  { row: 10, col: 9 },
  { row: 10, col: 8 },
  { row: 10, col: 7 },
  { row: 10, col: 6 },
  { row: 10, col: 5 },
  { row: 10, col: 4 },
  { row: 10, col: 3 },
  { row: 10, col: 2 },
  { row: 10, col: 1 },
  { row: 10, col: 0 },
  // Left column: bottom -> top (excluding bottom-left and top-left corners)
  { row: 9, col: 0 },
  { row: 8, col: 0 },
  { row: 7, col: 0 },
  { row: 6, col: 0 },
  { row: 5, col: 0 },
  { row: 4, col: 0 },
  { row: 3, col: 0 },
  { row: 2, col: 0 },
  { row: 1, col: 0 },
];
